# Generated by Django 4.2.30 on 2026-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finnet", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
