# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finnet", "0004_userprofile_privacy_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accounting_month_start_day",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
