import js from "@eslint/js";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";

const tsconfigRootDir = new URL(".", import.meta.url).pathname;

export default [
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      "src/api/schema.d.ts", // auto-generated by openapi-typescript
    ],
  },
  js.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir,
      },
      globals: {
        ...globals.browser,
        ...globals.es2022,
        // Injected at build time by Vite's `define` (see vite.config.js).
        __APP_VERSION__: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // React Compiler "readiness" rules (new in eslint-plugin-react-hooks
      // v7). The codebase predates them and many intentional patterns trip
      // them: reading a drag-origin ref during render to pick a CSS
      // transition (refs), syncing derived state from an effect
      // (set-state-in-effect), and accumulating a local `let` while mapping
      // SVG slices during render (immutability). Adopting the React Compiler
      // ruleset is a separate, behavior-sensitive effort; keep the
      // .jsx→.tsx migration scoped to type-safety by leaving these off for now.
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/immutability": "off",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
];
