[pytest]
DJANGO_SETTINGS_MODULE = finnet.settings
python_files = test_*.py
addopts = --reuse-db --cov=expenses --cov=portfolio --cov=finnet --cov-report=term-missing --cov-report=html:htmlcov

[coverage:run]
omit =
    */migrations/*
    */tests/*
    */test_*.py
    manage.py

[coverage:report]
skip_empty = True
