# Generated by Django 4.2.30 on 2026-04-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_allocationtarget"),
        ("expenses", "0003_recurringexpense_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="linked_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_expenses",
                to="portfolio.asset",
            ),
        ),
    ]
