# Generated by Django 4.2.30 on 2026-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_expense_linked_asset"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["date"], name="expenses_ex_date_17a2b2_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "date"], name="expenses_ex_categor_9e3535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["linked_asset", "date"], name="expenses_ex_linked__118d37_idx"
            ),
        ),
    ]
