# Generated by Django 4.2.30 on 2026-05-13 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0006_assign_owner_to_first_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ExpenseDescriptionSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("use_count", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_suggestions",
                        to="expenses.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="description_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at", "-use_count", "text"],
                "indexes": [
                    models.Index(
                        fields=["owner", "category", "-last_used_at"],
                        name="expenses_ex_owner_i_d08c32_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="expensedescriptionsuggestion",
            constraint=models.UniqueConstraint(
                fields=("owner", "category", "text"),
                name="unique_description_suggestion_per_owner_category_text",
            ),
        ),
    ]
