# Generated by Django 4.2.30 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0007_expense_is_verified_expensedescriptionsuggestion_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "date"],
                name="expenses_ex_owner_i_7060b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "is_verified", "date"],
                name="expenses_ex_owner_i_f7e8b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "category", "date"],
                name="expenses_ex_owner_i_17b108_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "linked_asset", "date"],
                name="expenses_ex_owner_i_5948da_idx",
            ),
        ),
    ]
