# Generated by Django 4.2.30 on 2026-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0009_recurring_v2_and_expense_recurrence_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recurringexpense",
            new_name="expenses_re_owner_i_c73c5e_idx",
            old_name="expenses_re_owner_i_4cc694_idx",
        ),
        migrations.RenameIndex(
            model_name="recurringexpense",
            new_name="expenses_re_owner_i_52aeb7_idx",
            old_name="expenses_re_owner_i_e9916b_idx",
        ),
    ]
