# Generated by Django 6.0.5 on 2026-06-01 16:48

from django.conf import settings
from django.db import migrations, models


def validate_existing_money(apps, schema_editor):
    Budget = apps.get_model("expenses", "Budget")
    Expense = apps.get_model("expenses", "Expense")
    RecurringExpense = apps.get_model("expenses", "RecurringExpense")
    issues = {
        "budgets_non_positive": Budget.objects.filter(amount__lte=0).count(),
        "expenses_non_positive": Expense.objects.filter(amount__lte=0).count(),
        "recurrings_non_positive": RecurringExpense.objects.filter(
            amount__lte=0
        ).count(),
        "recurrings_bad_day": RecurringExpense.objects.exclude(
            day_of_month__range=(1, 31)
        ).count(),
    }
    if any(issues.values()):
        raise RuntimeError(
            "Cannot add money constraints: repair existing rows first. "
            + ", ".join(f"{key}={value}" for key, value in issues.items())
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "expenses",
            "0010_rename_expenses_re_owner_i_4cc694_idx_expenses_re_owner_i_c73c5e_idx_and_more",
        ),
        ("portfolio", "0028_asset_price_source_auto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_money, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="budget_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="recurringexpense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="recurringexpense_day_valid",
            ),
        ),
    ]
