# Generated by Django 6.0.6 on 2026-06-14 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0011_budget_budget_amount_positive_and_more"),
        ("portfolio", "0039_opening_balance_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="frequency",
            field=models.CharField(
                choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                default="MONTHLY",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recurringexpense",
            name="month_of_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("month_of_year__isnull", True),
                    models.Q(("month_of_year__gte", 1), ("month_of_year__lte", 12)),
                    _connector="OR",
                ),
                name="recurringexpense_month_valid",
            ),
        ),
    ]
