# Generated by Django 6.0.6 on 2026-06-16 23:03

import fininzen.fields
from django.conf import settings
from django.db import migrations, models


def _backfill_text_bidx(apps, schema_editor):
    """Populate text_bidx for existing suggestion rows so the new uniqueness
    constraint (owner, category, text_bidx) holds and exact-match lookups work.

    Computed with whatever FIELD_ENCRYPTION_KEYS is configured at migrate time.
    The documented production path migrates into a fresh Postgres via
    ``migrate_sqlite_to_postgres`` (which recomputes the index on write under the
    prod key), so this branch matters mainly for in-place dev databases.
    """
    from fininzen import crypto

    Model = apps.get_model("expenses", "ExpenseDescriptionSuggestion")
    db = schema_editor.connection.alias
    rows = list(Model.objects.using(db).all())
    for obj in rows:
        obj.text_bidx = crypto.blind_index(obj.text or "")
    if rows:
        Model.objects.using(db).bulk_update(rows, ["text_bidx"], batch_size=500)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0012_recurringexpense_frequency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensedescriptionsuggestion",
            options={"ordering": ["-last_used_at", "-use_count", "id"]},
        ),
        migrations.AlterModelOptions(
            name="recurringexpense",
            options={
                "ordering": ["-start_date", "id"],
                "verbose_name": "Spesa Ricorrente",
                "verbose_name_plural": "Spese Ricorrenti",
            },
        ),
        migrations.RemoveConstraint(
            model_name="expensedescriptionsuggestion",
            name="unique_description_suggestion_per_owner_category_text",
        ),
        migrations.AddField(
            model_name="expensedescriptionsuggestion",
            name="text_bidx",
            field=fininzen.fields.BlindIndexField(
                default="", editable=False, max_length=64, source_field="text"
            ),
        ),
        migrations.AlterField(
            model_name="expensedescriptionsuggestion",
            name="text",
            field=fininzen.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="recurringexpense",
            name="description",
            field=fininzen.fields.EncryptedTextField(),
        ),
        migrations.RunPython(_backfill_text_bidx, _noop),
        migrations.AddConstraint(
            model_name="expensedescriptionsuggestion",
            constraint=models.UniqueConstraint(
                fields=("owner", "category", "text_bidx"),
                name="unique_description_suggestion_per_owner_category_text",
            ),
        ),
    ]
