# Generated by Django 6.0.6 on 2026-06-28 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0014_require_tenant_ownership"),
        ("portfolio", "0047_owner_cascade_on_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expense",
            name="expense_amount_positive",
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="expense_amount_nonzero",
            ),
        ),
    ]
