# Generated by Django 6.0.6 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0015_remove_expense_expense_amount_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringexpense",
            name="generation_lead_days",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddConstraint(
            model_name="recurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("generation_lead_days__gte", 0),
                    ("generation_lead_days__lte", 31),
                ),
                name="recurringexpense_lead_valid",
            ),
        ),
    ]
