import type { Language } from "../i18n";

// User-facing release notes. Deliberately separate from CHANGELOG.md: that file
// is generated by commitizen from Conventional Commits and speaks in scopes and
// commit types ("build(deps): bump webauthn from 2.7.1 to 3.0.0"), which is the
// wrong register for the person using the app. These are written by hand, in
// both languages, and only cover what a user would notice.
//
// See wiki/VERSIONING.md for how to add an entry.

export type ReleaseNote = {
    // "unreleased" until `just release` stamps it with the real number — the
    // version isn't known until commitizen computes it from the commits.
    version: string;
    // ISO YYYY-MM-DD. Stamped alongside the version by scripts/stamp_release_notes.py.
    date: string;
    highlights: Record<Language, string[]>;
};

export const UNRELEASED = "unreleased";

// Newest first. Only releases worth telling users about appear here: one that
// only bumped dependencies has no entry, and so shows no banner at all.
export const RELEASE_NOTES: ReleaseNote[] = [
    {
        version: UNRELEASED,
        date: "",
        highlights: {
            it: [
                "L'app aggiunta alla schermata Home torna ad aprirsi a schermo intero, senza la barra degli indirizzi e i tasti di Safari in basso, e mostra di nuovo la schermata di avvio. Per riaverla: elimina l'icona dalla Home e riaggiungila da Safari.",
            ],
            en: [
                "The app added to the Home Screen opens full screen again, without Safari's address bar and buttons at the bottom, and shows its launch screen once more. To get this back: delete the icon from the Home Screen and add it again from Safari.",
            ],
        },
    },
    {
        version: "0.6.2",
        date: "2026-07-16",
        highlights: {
            it: [
                "Sull'app installata sul telefono il contenuto non finisce più sotto la tacca e la barra di stato: i titoli in cima alle pagine sono di nuovo leggibili per intero.",
            ],
            en: [
                "On the phone app installed to the home screen, content no longer runs underneath the notch and the status bar: the titles at the top of each page are fully readable again.",
            ],
        },
    },
    {
        version: "0.6.1",
        date: "2026-07-16",
        highlights: {
            it: [
                "La pagina Novità ora ha un tasto per chiuderla: prima si poteva uscire solo toccando una voce della barra di navigazione in basso.",
                "La versione dell'app in Impostazioni → Info e nella schermata di accesso è ora sempre aggiornata, anche subito dopo un rilascio.",
            ],
            en: [
                "The What's new page now has a close button: before, the only way out was to tap an item in the bottom navigation bar.",
                "The app version in Settings → About and on the sign-in screen is now always current, even right after a release.",
            ],
        },
    },
    {
        version: "0.6.0",
        date: "2026-07-16",
        highlights: {
            it: [
                "I dati ora si aggiornano subito: prima l'app poteva mostrarti la situazione precedente alla tua ultima modifica, e i cambiamenti fatti da un altro dispositivo comparivano in ritardo.",
                "Su telefono le azioni Verifica e Annulla verifica della selezione multipla sono di nuovo raggiungibili: il loro menu si apriva fuori dallo schermo.",
                "Quando esce un aggiornamento, ora te lo diciamo: al primo accesso compare un avviso con le novità, e non torna più una volta chiuso.",
                "Nuova pagina Novità, raggiungibile anche da Impostazioni → Info.",
                "Versione e data di rilascio ora visibili nella schermata di accesso e in Impostazioni → Info.",
            ],
            en: [
                "Your data now updates right away: the app could previously show you the state from before your last change, and edits made on another device showed up late.",
                "On phones, the Verify and Unverify actions for multi-select are reachable again: their menu used to open off-screen.",
                "When an update ships we now tell you: a notice with what's new appears on your first visit, and stays gone once dismissed.",
                "A new What's new page, also reachable from Settings → About.",
                "The version and release date are now visible on the sign-in screen and in Settings → About.",
            ],
        },
    },
];

export const releaseNoteFor = (version: string): ReleaseNote | undefined =>
    RELEASE_NOTES.find((note) => note.version === version);
