import type { Language } from "../i18n";

// User-facing release notes. Deliberately separate from CHANGELOG.md: that file
// is generated by commitizen from Conventional Commits and speaks in scopes and
// commit types ("build(deps): bump webauthn from 2.7.1 to 3.0.0"), which is the
// wrong register for the person using the app. These are written by hand, in
// both languages, and only cover what a user would notice.
//
// See wiki/VERSIONING.md for how to add an entry.

export type ReleaseNote = {
    // "unreleased" until `just release` stamps it with the real number — the
    // version isn't known until commitizen computes it from the commits.
    version: string;
    // ISO YYYY-MM-DD. Stamped alongside the version by scripts/stamp_release_notes.py.
    date: string;
    highlights: Record<Language, string[]>;
};

export const UNRELEASED = "unreleased";

// Newest first. Only releases worth telling users about appear here: one that
// only bumped dependencies has no entry, and so shows no banner at all.
export const RELEASE_NOTES: ReleaseNote[] = [
    {
        version: "0.13.0",
        date: "2026-07-31",
        highlights: {
            it: [
                "Nuova voce in Impostazioni per cambiare l'email di accesso, confermando con la password attuale.",
                "Autenticazione a due fattori (TOTP): attivala da Impostazioni con un'app come Google Authenticator o Authy, scansionando il QR code; al primo accesso ricevi 10 codici di backup monouso da conservare in caso di perdita del telefono.",
                "Corretto Face ID su iPhone: la registrazione della chiave di accesso non mostra più il prompt «Passkey» di iCloud, ma torna a chiedere direttamente Face ID/Touch ID.",
                "Gli amministratori possono ora disattivare l'MFA o rimuovere i passkey di un utente che ha perso il dispositivo, per aiutarlo a recuperare l'accesso.",
            ],
            en: [
                "New entry in Settings to change your sign-in email, confirmed with your current password.",
                "Two-factor authentication (TOTP): turn it on from Settings with an app like Google Authenticator or Authy by scanning the QR code; on first setup you get 10 single-use backup codes to keep somewhere safe in case you lose your phone.",
                'Fixed Face ID on iPhone: registering a passkey no longer shows iCloud\'s "Passkey" prompt — it goes straight to Face ID/Touch ID again.',
                "Admins can now disable MFA or remove passkeys for a user who has lost their device, to help them recover access.",
            ],
        },
    },
    {
        version: "0.12.0",
        date: "2026-07-30",
        highlights: {
            it: [
                "Il pannello admin si arricchisce di tre nuove sezioni: Records (statistiche sui dati), Audit Log (cronologia delle azioni degli amministratori) e Stato del sistema (freschezza di prezzi/backup e controlli di integrità dei dati).",
            ],
            en: [
                "The admin portal gained three new sections: Records (data statistics), Audit Log (history of admin actions), and System Health (price/backup freshness and data-integrity checks).",
            ],
        },
    },
    {
        version: "0.11.4",
        date: "2026-07-27",
        highlights: {
            it: [
                "Interventi interni di rafforzamento della sicurezza dell'infrastruttura e dell'app.",
            ],
            en: [
                "Internal security hardening improvements to the app and infrastructure.",
            ],
        },
    },
    {
        version: "0.11.3",
        date: "2026-07-27",
        highlights: {
            it: [
                "Nella schermata di accesso, quando la tastiera o la barra degli indirizzi di Chrome su Android riducono lo spazio visibile, il pulsante «Esplora demo →» non si sovrappone più alla scritta del copyright in fondo alla pagina.",
            ],
            en: [
                "On the sign-in screen, when Android Chrome's keyboard or address bar shrinks the visible viewport, the “Explore Demo →” button no longer overlaps the copyright line at the bottom of the page.",
            ],
        },
    },
    {
        version: "0.11.2",
        date: "2026-07-27",
        highlights: {
            it: [
                "I campi importo non hanno più l'icona della calcolatrice né il pulsante «=»: il campo è tornato pulito, sia nei Movimenti sia negli Investimenti.",
                "Le operazioni si fanno ora direttamente dalla tastiera del telefono: appena tocchi un campo importo compare una barretta con +, −, × e ÷ proprio sopra i tasti, così i numeri li scrivi con il tastierino di sempre e l'operazione la componi senza aprire nulla. «=» calcola il totale.",
                "Su Android la tastiera non copre più la scheda: prima, aprendo «Nuova spesa» e toccando l'importo, data e pulsanti «Annulla»/«Aggiungi» finivano sotto la tastiera e la scheda non si poteva salvare. Ora la scheda si restringe sopra la tastiera come già faceva su iPhone.",
            ],
            en: [
                "The amount fields no longer carry a calculator icon or an “=” button: the field is clean again, in both Cash Flow and Investments.",
                "The maths now happens straight off the phone keyboard: touch an amount field and a slim bar with +, −, × and ÷ appears right above the keys, so you type the numbers on the usual number pad and build the operation without opening anything. “=” works out the total.",
                "On Android the keyboard no longer covers the sheet: opening “New expense” and tapping the amount used to push the date and the “Cancel”/“Add” buttons under the keyboard, leaving no way to save. The sheet now shrinks to sit above the keyboard, as it already did on iPhone.",
            ],
        },
    },
    {
        version: "0.11.1",
        date: "2026-07-26",
        highlights: {
            it: [
                "Modificando una transazione negli Investimenti, cambiare la data non blocca più il salvataggio: il prezzo per quota viene di nuovo recuperato da solo (prima succedeva solo per le nuove transazioni), e sotto il campo trovi scritto se è in corso il recupero o se per quella data — un weekend, un festivo — la quotazione non esiste e va inserita a mano.",
                "Se manca un dato obbligatorio, il pulsante «Aggiorna» non resta più spento e muto: ora si può premere e ti dice esattamente cosa manca, per esempio «Inserisci il prezzo per quota».",
                "Nelle schede degli Investimenti il titolo e i pulsanti «Annulla»/«Salva» restano ora fissi: non devi più scorrere fino in fondo per salvare o chiudere. Su schermi grandi i campi si dispongono su due colonne, così la scheda ci sta quasi tutta senza scorrere.",
                "La pagina Conti ora ha la stessa larghezza delle altre schede: passando da un tab all'altro il contenuto non si restringe più.",
                "I conti sono ora divisi per tipo, ciascuno con il proprio totale.",
            ],
            en: [
                "When editing an Investments transaction, changing the date no longer blocks saving: the price per share is fetched automatically again (before, that only happened for new transactions), and a line under the field now tells you whether the lookup is running or whether there is simply no quote for that date — a weekend or a holiday — and you have to type it in.",
                "When a required field is missing, the “Update” button is no longer greyed out and silent: you can press it and it tells you exactly what's missing, for example “Enter the price per share”.",
                "In the Investments sheets the title and the “Cancel”/“Save” buttons now stay pinned: no more scrolling to the bottom just to save or close. On large screens the fields are laid out in two columns, so most of the sheet fits without scrolling.",
                "The Accounts page is now the same width as the other tabs: switching between tabs no longer makes the content shrink.",
                "Accounts are now split by account type, each with its own total.",
            ],
        },
    },
    {
        version: "0.11.0",
        date: "2026-07-25",
        highlights: {
            it: [
                "Nei Movimenti e negli Investimenti i filtri ora funzionano allo stesso modo e non si applicano più da soli: scegli conto, categoria, periodo o tipo e la modifica resta in bozza finché non tocchi «Applica filtri» — «Annulla», lo sfondo, Esc o trascinare la scheda in basso annullano invece la modifica.",
                "Corretto il filtro «Anno» negli Investimenti, che prima non aveva alcun effetto: ora mostra una griglia di 12 anni tra cui scegliere e applica subito il periodo selezionato.",
                "La scheda «Nuova transazione» del portafoglio è stata rinnovata: i menu di conto/attività ora sono coerenti con il resto dell'app (niente più popup bianco nel tema scuro), e prezzo, commissioni e tasse hanno la stessa calcolatrice già disponibile nei Movimenti.",
            ],
            en: [
                "In Cash Flow and Investments the filters now behave the same way and no longer apply themselves: pick account, category, period or type and the change stays in draft until you tap “Apply filters” — “Cancel”, the backdrop, Esc, or dragging the sheet down all discard it instead.",
                "Fixed the “Year” filter in Investments, which previously had no effect: it now shows a 12-year grid to choose from and applies the selected period immediately.",
                "The Portfolio “New transaction” sheet has been refreshed: the account/asset menus now match the rest of the app (no more white popup in dark mode), and price, fees and tax use the same calculator already available in Cash Flow.",
            ],
        },
    },
    {
        version: "0.10.0",
        date: "2026-07-25",
        highlights: {
            it: [
                "Nei campi importo dei Flussi (nuova spesa, entrata, trasferimento e modifica di un trasferimento) puoi ora fare il conto sul posto: scrivi direttamente l'operazione — per esempio «12,50+8,30» — e premi «=» o Invio per sostituirla con il totale, senza più calcolarlo a parte.",
                "Accanto al campo c'è anche una calcolatrice: si apre con un tocco e ha i tasti +, −, × e ÷, che sul telefono la tastiera numerica non offre. «Applica» porta il risultato nel campo.",
                "Il risultato deve restare positivo: un'operazione come «10−15» viene segnalata come errore invece di finire nel campo senza il segno meno.",
            ],
            en: [
                "The amount fields in Cash Flow (new expense, income, transfer, and editing a transfer) now do the maths for you: type the operation straight in — say “12.50+8.30” — and press “=” or Enter to replace it with the total, instead of working it out elsewhere.",
                "There is also a calculator next to the field: one tap opens it, with the +, −, × and ÷ keys the phone number pad doesn't offer. “Apply” puts the result into the field.",
                "The result has to stay positive: an operation like “10−15” is flagged as an error rather than landing in the field with its minus sign dropped.",
            ],
        },
    },
    {
        version: "0.9.2",
        date: "2026-07-24",
        highlights: {
            it: [
                "I menu per scegliere categoria, conto o attività collegata (quando aggiungi una spesa, un'entrata o un trasferimento) ora mostrano l'elenco completo e scorrono in modo fluido: prima la lista veniva tagliata e lo scorrimento faceva i capricci, soprattutto su iPhone.",
                "Su telefono lo stesso menu è più alto e resta agganciato al campo, e la voce di reset («Nessun collegamento» / «Nessuna categoria») è stata spostata in fondo alla lista.",
            ],
            en: [
                "The menus for choosing a category, account or linked asset (when adding an expense, income or transfer) now show the full list and scroll smoothly: before, the list was cut off and scrolling was glitchy, especially on iPhone.",
                "On phones the same menu is taller and stays anchored to the field, and the reset option (“No link” / “No category”) has been moved to the bottom of the list.",
            ],
        },
    },
    {
        version: "0.9.1",
        date: "2026-07-24",
        highlights: {
            it: [
                "I menu per scegliere il conto o l'attività collegata (quando aggiungi un movimento o un trasferimento) ora seguono sempre il tema scuro dell'app: niente più elenco con lo sfondo bianco, su qualsiasi browser — anche su Chrome/Windows con un tema scuro installato.",
            ],
            en: [
                "The menus for choosing the account or linked asset (when adding a transaction or a transfer) now always follow the app's dark theme: no more white-background list, in any browser — including Chrome/Windows with a dark theme installed.",
            ],
        },
    },
    {
        version: "0.9.0",
        date: "2026-07-24",
        highlights: {
            it: [
                "Nella dashboard la scheda «Categoria Cash Flow» mostra ora tutte le categorie invece di fermarsi alle prime cinque e raggruppare il resto in «Altro»: l'elenco scorre dentro la scheda e ogni voce apre i Flussi già filtrati su quella categoria. Vale sia per le Uscite che per le Entrate.",
                "La scheda principale dei Flussi mette ora in primo piano il saldo del mese (prima ripeteva la spesa già indicata sotto), con una barra che spiega quanto hai speso rispetto alle entrate: quanto hai risparmiato o, se hai speso più di quanto è entrato, di quanto sei in deficit.",
            ],
            en: [
                "On the dashboard, the “Cash Flow category” card now shows every category instead of stopping at the top five and lumping the rest into “Other”: the list scrolls inside the card and each row opens the Cash Flow already filtered to that category. This applies to both Expenses and Income.",
                "The main Cash Flow card now leads with the month's balance (it used to repeat the spend already shown below), with a bar that explains how much you spent against your income — how much you saved, or by how much you're in deficit if you spent more than came in.",
            ],
        },
    },
    {
        version: "0.8.1",
        date: "2026-07-24",
        highlights: {
            it: [
                "Nel tema scuro i menu a tendina per scegliere il conto o l'attività collegata (aggiunta di un movimento o di un trasferimento) non appaiono più con lo sfondo bianco: ora seguono il tema scuro dell'app, anche su Chrome/Windows con un tema scuro del browser installato.",
            ],
            en: [
                "In dark mode the drop-down menus for choosing the account or linked asset (when adding a transaction or a transfer) no longer show up with a white background: they now follow the app's dark theme, including on Chrome/Windows with a dark browser theme installed.",
            ],
        },
    },
    {
        version: "0.8.0",
        date: "2026-07-23",
        highlights: {
            it: [
                "La pagina Investimenti ha ora lo stesso stile della pagina Movimenti: cifre e titoli più leggibili, selettore del mese in evidenza in alto e icone colorate per tipo di attività.",
                'Nuova icona dell\'app: il monogramma "F" sostituisce la vecchia icona su schermata Home, PWA e Safari.',
            ],
            en: [
                "The Investments page now matches the look of the Cash Flow page: larger, easier-to-read figures and titles, the month selector highlighted at the top, and colour-coded icons by asset type.",
                'New app icon: the "F" monogram replaces the old icon on the Home Screen, in the PWA and in Safari.',
            ],
        },
    },
    {
        version: "0.7.2",
        date: "2026-07-22",
        highlights: {
            it: [
                "Su iPhone i campi di ricerca dei movimenti (cashflow) e delle transazioni degli investimenti non ingrandiscono più la pagina quando li tocchi.",
            ],
            en: [
                "On iPhone the search fields for transactions (cashflow) and for investment transactions no longer zoom the page when you tap them.",
            ],
        },
    },
    {
        version: "0.7.1",
        date: "2026-07-22",
        highlights: {
            it: [
                "Su iPhone il campo di ricerca delle categorie non ingrandisce più la pagina quando lo tocchi.",
                "Nei filtri l'elenco delle categorie ora si apre per intero invece di mostrarne solo due o tre alla volta.",
            ],
            en: [
                "On iPhone the category search field no longer zooms the page when you tap it.",
                "In the filters, the category list now opens in full instead of showing only two or three at a time.",
            ],
        },
    },
    {
        version: "0.7.0",
        date: "2026-07-21",
        highlights: {
            it: [
                'Nuovo look "Quiet Ledger": palette neutra carta/grafite, font Inter e tipografia più sobria, con bordi e ombre più leggeri al posto dei bagliori azzurri.',
                "Su desktop l'app usa finalmente layout a più colonne invece della versione mobile allargata: dashboard, movimenti, portafoglio e FIRE sfruttano lo spazio; su telefono nulla cambia.",
                'Nuovo indicatore "Tasso di risparmio" nella dashboard desktop.',
                "Feed dei movimenti più arioso: righe più alte, selettore del periodo in cima al riepilogo e netto del giorno su ogni separatore giornaliero.",
                'La card "Categorie" in dashboard raggruppa ora le spese per categoria principale: tocca una voce per vedere il dettaglio delle sottocategorie o aprire il feed già filtrato.',
                "Nel menu di scelta della categoria ora puoi cercare digitando, comodo quando hai molte categorie e sottocategorie.",
                "Corretto il nome del mese contabile: con un giorno d'inizio mese avanzato (es. 26) i periodi mostravano un mese indietro; ora riportano il mese corretto (i totali erano già giusti).",
            ],
            en: [
                'A new "Quiet Ledger" look: a neutral paper/graphite palette, the Inter typeface and quieter typography, with lighter borders and shadows in place of the azure glows.',
                "On desktop the app finally uses real multi-column layouts instead of the stretched phone view: dashboard, transactions, portfolio and FIRE make use of the space; nothing changes on phones.",
                'A new "Savings Rate" indicator on the desktop dashboard.',
                "A calmer transactions feed: taller rows, the period selector at the top of the summary, and the day's net on each daily divider.",
                'The dashboard "Categories" card now groups spending by top-level category: tap a row to see its subcategory breakdown, or to open the feed already filtered.',
                "The category picker now has type-to-search, handy when you have many categories and subcategories.",
                "Fixed the accounting-month label: with a late month-start day (e.g. 26) periods showed a month behind; they now show the correct month (totals were always right).",
            ],
        },
    },
    {
        version: "0.6.3",
        date: "2026-07-16",
        highlights: {
            it: [
                "L'app aggiunta alla schermata Home torna ad aprirsi a schermo intero, senza la barra degli indirizzi e i tasti di Safari in basso, e mostra di nuovo la schermata di avvio. Per riaverla: elimina l'icona dalla Home e riaggiungila da Safari.",
            ],
            en: [
                "The app added to the Home Screen opens full screen again, without Safari's address bar and buttons at the bottom, and shows its launch screen once more. To get this back: delete the icon from the Home Screen and add it again from Safari.",
            ],
        },
    },
    {
        version: "0.6.2",
        date: "2026-07-16",
        highlights: {
            it: [
                "Sull'app installata sul telefono il contenuto non finisce più sotto la tacca e la barra di stato: i titoli in cima alle pagine sono di nuovo leggibili per intero.",
            ],
            en: [
                "On the phone app installed to the home screen, content no longer runs underneath the notch and the status bar: the titles at the top of each page are fully readable again.",
            ],
        },
    },
    {
        version: "0.6.1",
        date: "2026-07-16",
        highlights: {
            it: [
                "La pagina Novità ora ha un tasto per chiuderla: prima si poteva uscire solo toccando una voce della barra di navigazione in basso.",
                "La versione dell'app in Impostazioni → Info e nella schermata di accesso è ora sempre aggiornata, anche subito dopo un rilascio.",
            ],
            en: [
                "The What's new page now has a close button: before, the only way out was to tap an item in the bottom navigation bar.",
                "The app version in Settings → About and on the sign-in screen is now always current, even right after a release.",
            ],
        },
    },
    {
        version: "0.6.0",
        date: "2026-07-16",
        highlights: {
            it: [
                "I dati ora si aggiornano subito: prima l'app poteva mostrarti la situazione precedente alla tua ultima modifica, e i cambiamenti fatti da un altro dispositivo comparivano in ritardo.",
                "Su telefono le azioni Verifica e Annulla verifica della selezione multipla sono di nuovo raggiungibili: il loro menu si apriva fuori dallo schermo.",
                "Quando esce un aggiornamento, ora te lo diciamo: al primo accesso compare un avviso con le novità, e non torna più una volta chiuso.",
                "Nuova pagina Novità, raggiungibile anche da Impostazioni → Info.",
                "Versione e data di rilascio ora visibili nella schermata di accesso e in Impostazioni → Info.",
            ],
            en: [
                "Your data now updates right away: the app could previously show you the state from before your last change, and edits made on another device showed up late.",
                "On phones, the Verify and Unverify actions for multi-select are reachable again: their menu used to open off-screen.",
                "When an update ships we now tell you: a notice with what's new appears on your first visit, and stays gone once dismissed.",
                "A new What's new page, also reachable from Settings → About.",
                "The version and release date are now visible on the sign-in screen and in Settings → About.",
            ],
        },
    },
];

export const releaseNoteFor = (version: string): ReleaseNote | undefined =>
    RELEASE_NOTES.find((note) => note.version === version);
