import type { Language } from "../i18n";

// User-facing release notes. Deliberately separate from CHANGELOG.md: that file
// is generated by commitizen from Conventional Commits and speaks in scopes and
// commit types ("build(deps): bump webauthn from 2.7.1 to 3.0.0"), which is the
// wrong register for the person using the app. These are written by hand, in
// both languages, and only cover what a user would notice.
//
// See wiki/VERSIONING.md for how to add an entry.

export type ReleaseNote = {
    // "unreleased" until `just release` stamps it with the real number — the
    // version isn't known until commitizen computes it from the commits.
    version: string;
    // ISO YYYY-MM-DD. Stamped alongside the version by scripts/stamp_release_notes.py.
    date: string;
    highlights: Record<Language, string[]>;
};

export const UNRELEASED = "unreleased";

// Newest first. Only releases worth telling users about appear here: one that
// only bumped dependencies has no entry, and so shows no banner at all.
export const RELEASE_NOTES: ReleaseNote[] = [
    {
        version: UNRELEASED,
        date: "",
        highlights: {
            it: [
                'Nuovo look "Quiet Ledger": palette neutra carta/grafite, font Inter e tipografia più sobria, con bordi e ombre più leggeri al posto dei bagliori azzurri.',
                "Su desktop l'app usa finalmente layout a più colonne invece della versione mobile allargata: dashboard, movimenti, portafoglio e FIRE sfruttano lo spazio; su telefono nulla cambia.",
                'Nuovo indicatore "Tasso di risparmio" nella dashboard desktop.',
                "Feed dei movimenti più arioso: righe più alte, selettore del periodo in cima al riepilogo e netto del giorno su ogni separatore giornaliero.",
                'La card "Categorie" in dashboard raggruppa ora le spese per categoria principale: tocca una voce per vedere il dettaglio delle sottocategorie o aprire il feed già filtrato.',
                "Nel menu di scelta della categoria ora puoi cercare digitando, comodo quando hai molte categorie e sottocategorie.",
                "Corretto il nome del mese contabile: con un giorno d'inizio mese avanzato (es. 26) i periodi mostravano un mese indietro; ora riportano il mese corretto (i totali erano già giusti).",
            ],
            en: [
                'A new "Quiet Ledger" look: a neutral paper/graphite palette, the Inter typeface and quieter typography, with lighter borders and shadows in place of the azure glows.',
                "On desktop the app finally uses real multi-column layouts instead of the stretched phone view: dashboard, transactions, portfolio and FIRE make use of the space; nothing changes on phones.",
                'A new "Savings Rate" indicator on the desktop dashboard.',
                "A calmer transactions feed: taller rows, the period selector at the top of the summary, and the day's net on each daily divider.",
                'The dashboard "Categories" card now groups spending by top-level category: tap a row to see its subcategory breakdown, or to open the feed already filtered.',
                "The category picker now has type-to-search, handy when you have many categories and subcategories.",
                "Fixed the accounting-month label: with a late month-start day (e.g. 26) periods showed a month behind; they now show the correct month (totals were always right).",
            ],
        },
    },
    {
        version: "0.6.3",
        date: "2026-07-16",
        highlights: {
            it: [
                "L'app aggiunta alla schermata Home torna ad aprirsi a schermo intero, senza la barra degli indirizzi e i tasti di Safari in basso, e mostra di nuovo la schermata di avvio. Per riaverla: elimina l'icona dalla Home e riaggiungila da Safari.",
            ],
            en: [
                "The app added to the Home Screen opens full screen again, without Safari's address bar and buttons at the bottom, and shows its launch screen once more. To get this back: delete the icon from the Home Screen and add it again from Safari.",
            ],
        },
    },
    {
        version: "0.6.2",
        date: "2026-07-16",
        highlights: {
            it: [
                "Sull'app installata sul telefono il contenuto non finisce più sotto la tacca e la barra di stato: i titoli in cima alle pagine sono di nuovo leggibili per intero.",
            ],
            en: [
                "On the phone app installed to the home screen, content no longer runs underneath the notch and the status bar: the titles at the top of each page are fully readable again.",
            ],
        },
    },
    {
        version: "0.6.1",
        date: "2026-07-16",
        highlights: {
            it: [
                "La pagina Novità ora ha un tasto per chiuderla: prima si poteva uscire solo toccando una voce della barra di navigazione in basso.",
                "La versione dell'app in Impostazioni → Info e nella schermata di accesso è ora sempre aggiornata, anche subito dopo un rilascio.",
            ],
            en: [
                "The What's new page now has a close button: before, the only way out was to tap an item in the bottom navigation bar.",
                "The app version in Settings → About and on the sign-in screen is now always current, even right after a release.",
            ],
        },
    },
    {
        version: "0.6.0",
        date: "2026-07-16",
        highlights: {
            it: [
                "I dati ora si aggiornano subito: prima l'app poteva mostrarti la situazione precedente alla tua ultima modifica, e i cambiamenti fatti da un altro dispositivo comparivano in ritardo.",
                "Su telefono le azioni Verifica e Annulla verifica della selezione multipla sono di nuovo raggiungibili: il loro menu si apriva fuori dallo schermo.",
                "Quando esce un aggiornamento, ora te lo diciamo: al primo accesso compare un avviso con le novità, e non torna più una volta chiuso.",
                "Nuova pagina Novità, raggiungibile anche da Impostazioni → Info.",
                "Versione e data di rilascio ora visibili nella schermata di accesso e in Impostazioni → Info.",
            ],
            en: [
                "Your data now updates right away: the app could previously show you the state from before your last change, and edits made on another device showed up late.",
                "On phones, the Verify and Unverify actions for multi-select are reachable again: their menu used to open off-screen.",
                "When an update ships we now tell you: a notice with what's new appears on your first visit, and stays gone once dismissed.",
                "A new What's new page, also reachable from Settings → About.",
                "The version and release date are now visible on the sign-in screen and in Settings → About.",
            ],
        },
    },
];

export const releaseNoteFor = (version: string): ReleaseNote | undefined =>
    RELEASE_NOTES.find((note) => note.version === version);
