[fininzen-auth]
enabled  = true
backend  = polling
logpath  = /var/log/caddy_access.log
filter   = fininzen-auth
maxretry = 20
findtime = 60
bantime  = 900
banaction = nftables-multiport
port      = http,https
