# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0003_userprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="privacy_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
