# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0005_userprofile_accounting_month_start_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enabled_features",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
