# Generated by Django 6.0.6 on 2026-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0009_demoseedstate_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_config",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
