# Generated by Django 6.0.6 on 2026-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0010_userprofile_dashboard_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="transaction_preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
