# Generated by Django 6.0.6 on 2026-06-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fininzen", "0011_userprofile_transaction_preferences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webauthnchallenge",
            new_name="fininzen_we_user_id_90dee4_idx",
            old_name="fininzen_weba_user_id_6daff7_idx",
        ),
    ]
