# Generated by Django 6.0.7 on 2026-07-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fininzen",
            "0012_rename_fininzen_weba_user_id_6daff7_idx_fininzen_we_user_id_90dee4_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_seen_release",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
