# Generated by Django 6.0.7 on 2026-07-28 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_users(apps, schema_editor):
    """Existing accounts predate the approval gate — don't lock them out.

    Filtering on status="pending" (not .all()) keeps this idempotent if the
    migration is ever re-run against a partially-applied state.
    """
    UserProfile = apps.get_model("fininzen", "UserProfile")
    UserProfile.objects.filter(status="pending").update(status="approved")


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0013_userprofile_last_seen_release"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            approve_existing_users, reverse_code=migrations.RunPython.noop
        ),
    ]
