# Generated by Django 6.0.7 on 2026-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0014_userprofile_status_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
