# Generated by Django 6.0.7 on 2026-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fininzen", "0018_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
