# Generated by Django 6.0.7 on 2026-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fininzen", "0019_userprofile_terms_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="terms_rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
