"""migrate_sqlite_to_postgres — one-shot data migration from the legacy SQLite DB
into the configured ``default`` database (Postgres in production).

Why a Django command and not a raw copy: sensitive fields are encrypted at the
application layer (see ``finnet.crypto``), so the rows must be written *through the
ORM* — only then does ``EncryptedTextField`` produce ciphertext and
``BlindIndexField`` populate its index in the target. A file-level copy would carry
the old plaintext across untouched.

Properties:
- Primary keys are preserved (``bulk_create`` with explicit ids).
- No model signals fire (``bulk_create``/``bulk_update`` don't send post_save).
- ``auto_now``/``auto_now_add`` timestamps are frozen so created_at etc. survive.
- Self/cyclic FKs are filled in a second pass (Category.parent,
  Asset.source_account/previous_account, AssetTransaction.derived_from).
- Postgres sequences are realigned after the load.

Usage:
    manage.py migrate_sqlite_to_postgres --sqlite-path /path/db.sqlite3 --dry-run
    manage.py migrate_sqlite_to_postgres --sqlite-path /path/db.sqlite3 --apply
    manage.py migrate_sqlite_to_postgres --sqlite-path /path/db.sqlite3 --verify-only

Operate with the app in maintenance and the target schema already migrated
(``manage.py migrate`` against the empty Postgres) before ``--apply``.
"""

from __future__ import annotations

import os
from contextlib import contextmanager
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.core.management.color import no_style
from django.db import connections, models, transaction

from finnet import crypto

LEGACY_ALIAS = "legacy_sqlite"
DEST_ALIAS = "default"

# Self/cyclic foreign keys filled in a second pass (their targets are rows in the
# same table, which may not exist yet during the first bulk_create).
SELF_FK_DEFERRED = {
    "expenses.Category": ["parent_id"],
    "portfolio.Asset": ["source_account_id", "previous_account_id"],
    "portfolio.AssetTransaction": ["derived_from_id"],
}

# Topological copy order: every cross-model FK target appears before the rows that
# point at it. Self-FKs above are deferred so order within a table doesn't matter.
COPY_ORDER = [
    "auth.User",
    "portfolio.InvestmentType",
    "portfolio.ContributionSource",
    "portfolio.Asset",
    "expenses.Category",
    "expenses.RecurringExpense",
    "expenses.Expense",
    "portfolio.RecurringInvestmentPlan",
    "portfolio.AssetTransaction",
    "portfolio.AssetContributionSource",
    "portfolio.AssetPriceHistory",
    "portfolio.PortfolioSnapshot",
    "portfolio.FXRateHistory",
    "portfolio.AllocationTarget",
    "portfolio.DashboardSummary",
    "portfolio.FireSettings",
    "expenses.ExpenseDescriptionSuggestion",
    "expenses.Budget",
    "finnet.UserProfile",
    "finnet.DataAccessGrant",
    "finnet.DemoSeedState",
    "finnet.WebAuthnCredential",
]

# Deliberately NOT migrated (users simply re-authenticate after the switch):
# sessions, JWT outstanding/blacklist tokens, WebAuthnChallenge (ephemeral),
# ContentType/Permission/Group (regenerated by `migrate`). User M2M (groups,
# user_permissions) is unused by this app and is not copied.


@contextmanager
def _frozen_auto_now(model_list):
    """Disable auto_now/auto_now_add on every datetime field so the legacy
    timestamps are written verbatim instead of being reset to 'now'."""
    changed = []
    for model in model_list:
        for f in model._meta.fields:
            if isinstance(f, models.DateTimeField) and (f.auto_now or f.auto_now_add):
                changed.append((f, f.auto_now, f.auto_now_add))
                f.auto_now = False
                f.auto_now_add = False
    try:
        yield
    finally:
        for f, an, ana in changed:
            f.auto_now = an
            f.auto_now_add = ana


class Command(BaseCommand):
    help = "Migrate data from the legacy SQLite database into the default database."

    def add_arguments(self, parser):
        parser.add_argument(
            "--sqlite-path",
            default=os.environ.get("DB_PATH", str(settings.BASE_DIR / "db.sqlite3")),
            help="Path to the source SQLite file (default: env DB_PATH or db.sqlite3).",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Perform the migration (write rows into the default DB).",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Read and count rows without writing anything (default if no mode given).",
        )
        parser.add_argument(
            "--verify-only",
            action="store_true",
            help="Compare per-model row counts between source and destination.",
        )
        parser.add_argument("--batch-size", type=int, default=500)
        parser.add_argument(
            "--force",
            action="store_true",
            help="Allow --apply even if the destination already has user rows "
            "(Phase 0 wipes them first). Off by default to prevent clobbering a "
            "populated database by accident.",
        )
        parser.add_argument(
            "--allow-plaintext",
            action="store_true",
            help="Allow --apply into a Postgres target with no FIELD_ENCRYPTION_KEYS "
            "configured (sensitive fields would be written in PLAINTEXT). Off by "
            "default so a missing key can't silently bypass encryption.",
        )

    # ── helpers ──────────────────────────────────────────────────────────────
    def _models(self):
        return [apps.get_model(label) for label in COPY_ORDER]

    def _legacy_table_names(self):
        conn = connections[LEGACY_ALIAS]
        with conn.cursor() as cur:
            return set(conn.introspection.table_names(cur))

    def _legacy_columns(self, model):
        conn = connections[LEGACY_ALIAS]
        with conn.cursor() as cur:
            desc = conn.introspection.get_table_description(cur, model._meta.db_table)
        return {col.name for col in desc}

    def _register_legacy_connection(self, sqlite_path):
        connections.databases[LEGACY_ALIAS] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(sqlite_path),
            "OPTIONS": {"timeout": 30},
            "ATOMIC_REQUESTS": False,
            "AUTOCOMMIT": True,
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": False,
            "TIME_ZONE": None,
        }

    # ── main ─────────────────────────────────────────────────────────────────
    def handle(self, *args, **opts):
        sqlite_path = Path(opts["sqlite_path"]).expanduser()
        apply = opts["apply"]
        verify_only = opts["verify_only"]
        dry_run = opts["dry_run"] or not (apply or verify_only)
        batch_size = opts["batch_size"]

        if not sqlite_path.is_file():
            raise CommandError(f"SQLite source not found: {sqlite_path}")

        self._register_legacy_connection(sqlite_path)
        dest = connections[DEST_ALIAS]

        # Sanity: source and destination must be different databases.
        if (
            dest.vendor == "sqlite"
            and dest.settings_dict.get("NAME")
            and Path(str(dest.settings_dict["NAME"])).resolve() == sqlite_path.resolve()
        ):
            raise CommandError(
                "Destination 'default' points at the SQLite source itself. "
                "Configure DATABASE_URL/POSTGRES_* for the target before migrating."
            )
        if dest.vendor != "postgresql":
            self.stdout.write(
                self.style.WARNING(
                    f"Destination is '{dest.vendor}', not postgresql — proceeding "
                    "(sequence realignment will be skipped)."
                )
            )

        model_list = self._models()
        legacy_tables = self._legacy_table_names()
        missing = [m for m in model_list if m._meta.db_table not in legacy_tables]
        for m in missing:
            self.stdout.write(
                self.style.WARNING(
                    f"  skip {m._meta.label}: table '{m._meta.db_table}' absent in source"
                )
            )
        model_list = [m for m in model_list if m not in missing]

        if verify_only:
            if not self._verify(model_list):
                raise CommandError("Row-count verification FAILED — see above.")
            return

        if not apply:
            self.stdout.write(
                self.style.WARNING("DRY-RUN — no rows will be written.\n")
            )
        else:
            # Guard 1: don't write sensitive fields in plaintext into a real
            # (Postgres) target just because the key wasn't exported. Phase 1
            # copies through the ORM, so a missing key silently disables
            # encryption — refuse unless the operator opts in explicitly.
            if dest.vendor == "postgresql" and not crypto.is_encryption_enabled():
                if not opts["allow_plaintext"]:
                    raise CommandError(
                        "Refusing to --apply into Postgres with no FIELD_ENCRYPTION_KEYS: "
                        "sensitive fields would be written in PLAINTEXT. Export the key "
                        "first, or pass --allow-plaintext to override (dev only)."
                    )
                self.stdout.write(
                    self.style.WARNING(
                        "Encryption DISABLED (--allow-plaintext) — sensitive fields "
                        "will be written in PLAINTEXT."
                    )
                )
            elif crypto.is_encryption_enabled():
                self.stdout.write(
                    "Encryption ENABLED — sensitive fields will be written encrypted."
                )
            else:
                self.stdout.write(
                    self.style.WARNING(
                        "Encryption DISABLED (no FIELD_ENCRYPTION_KEYS) — sensitive "
                        "fields will be written in PLAINTEXT. Abort unless this is dev."
                    )
                )

            # Guard 2: Phase 0 wipes the destination. Refuse to run against a DB
            # that already holds real data unless the operator forces it, so a
            # stray re-run can't clobber a populated database. Checked via
            # auth.User: a freshly-migrated target has zero users (the only seed
            # rows `migrate` creates are InvestmentTypes), while a previously
            # loaded one does — so the documented migrate→apply flow still works.
            user_model = apps.get_model("auth", "User")
            existing_users = user_model.objects.using(DEST_ALIAS).count()
            if existing_users and not opts["force"]:
                raise CommandError(
                    f"Destination already has {existing_users} user(s). --apply clears "
                    "the destination first; pass --force if you intend to replace it."
                )

        self_fk_map: dict = {}
        total = 0

        def _run():
            nonlocal total
            with _frozen_auto_now(model_list):
                # Phase 0: clear any rows the target's own migrations seeded
                # (e.g. default InvestmentTypes from portfolio/0002). Reverse
                # topological order + raw delete keeps DB-level FKs satisfied and
                # fires no signals/cascades.
                if not dry_run:
                    for model in reversed(model_list):
                        model.objects.using(DEST_ALIAS).all()._raw_delete(
                            using=DEST_ALIAS
                        )
                # Phase 1: copy every row (self-FKs nulled, captured for phase 2).
                for model in model_list:
                    n = self._copy_model(model, batch_size, dry_run, self_fk_map)
                    total += n
                    self.stdout.write(f"  {model._meta.label:<40} {n:>7} rows")
                # Phase 2: backfill the deferred self/cyclic FKs.
                for model in model_list:
                    self._apply_self_fks(
                        model, self_fk_map.get(model, {}), batch_size, dry_run
                    )

        if dry_run:
            _run()
        else:
            with transaction.atomic(using=DEST_ALIAS):
                _run()
            self._reset_sequences(model_list)

        self.stdout.write("")
        self.stdout.write(self.style.SUCCESS(f"Total rows: {total}"))
        if not dry_run:
            self.stdout.write("Verifying counts…")
            ok = self._verify(model_list)
            if not ok:
                raise CommandError(
                    "Row-count verification FAILED — see mismatches above."
                )
            self.stdout.write(self.style.SUCCESS("Migration complete and verified."))
        else:
            self.stdout.write(
                self.style.WARNING("Dry-run only — re-run with --apply to write.")
            )

    def _copy_model(self, model, batch_size, dry_run, self_fk_map):
        legacy_cols = self._legacy_columns(model)
        read_fields = [
            f.attname for f in model._meta.concrete_fields if f.column in legacy_cols
        ]
        deferred_attnames = set(SELF_FK_DEFERRED.get(model._meta.label, []))

        rows = model.objects.using(LEGACY_ALIAS).values(*read_fields)
        instances = []
        deferred_rows: dict = {}
        for row in rows.iterator():
            kwargs = {}
            for fn in read_fields:
                if fn in deferred_attnames:
                    if row[fn] is not None:
                        deferred_rows.setdefault(row["id"], {})[fn] = row[fn]
                    kwargs[fn] = None
                else:
                    kwargs[fn] = row[fn]
            instances.append(model(**kwargs))

        if not dry_run and instances:
            model.objects.using(DEST_ALIAS).bulk_create(
                instances, batch_size=batch_size
            )
        self_fk_map[model] = deferred_rows
        return len(instances)

    def _apply_self_fks(self, model, deferred_rows, batch_size, dry_run):
        if dry_run or not deferred_rows:
            return
        instances = []
        fields = set()
        for pk, fks in deferred_rows.items():
            instances.append(model(id=pk, **fks))
            fields.update(fks.keys())
        model.objects.using(DEST_ALIAS).bulk_update(
            instances, list(fields), batch_size=batch_size
        )

    def _reset_sequences(self, model_list):
        dest = connections[DEST_ALIAS]
        if dest.vendor != "postgresql":
            return
        sql_list = dest.ops.sequence_reset_sql(no_style(), model_list)
        if not sql_list:
            return
        with dest.cursor() as cur:
            for sql in sql_list:
                cur.execute(sql)
        self.stdout.write(f"  realigned {len(sql_list)} Postgres sequence(s)")

    def _verify(self, model_list):
        all_ok = True
        self.stdout.write("")
        self.stdout.write(f"  {'model':<40} {'source':>8} {'dest':>8}  status")
        for model in model_list:
            src = model.objects.using(LEGACY_ALIAS).count()
            dst = model.objects.using(DEST_ALIAS).count()
            ok = src == dst
            all_ok = all_ok and ok
            style = self.style.SUCCESS if ok else self.style.ERROR
            self.stdout.write(
                style(
                    f"  {model._meta.label:<40} {src:>8} {dst:>8}  "
                    f"{'OK' if ok else 'MISMATCH'}"
                )
            )
        return all_ok
