import { groupAssets } from "./derivedDataModel";
import { useCatalogActions } from "./useCatalogActions";
import { useDerivedAppData } from "./useDerivedAppData";
import { useFinancialActions } from "./useFinancialActions";
import { useImportAndTicker } from "./useImportAndTicker";
import { useRecurringActions } from "./useRecurringActions";
import { useResetActions } from "./useResetActions";
import { useAppBootstrap } from "./useAppBootstrap";
import type { AppProviderState } from "./useAppProviderState";
import type { SessionController } from "./useSessionController";
import type { ThemeController } from "./useThemeLang";
import type { useAppDataControllers } from "./useAppDataControllers";

type UseAppActionControllersArgs = {
    providerState: AppProviderState;
    sessionController: SessionController;
    themeController: ThemeController;
    dataControllers: ReturnType<typeof useAppDataControllers>;
};

export function useAppActionControllers({
    providerState,
    sessionController,
    themeController,
    dataControllers,
}: UseAppActionControllersArgs) {
    const { MONTHS, T } = themeController;
    const {
        adjustAssetId,
        adjustForm,
        assetForm,
        assetSaving,
        assets,
        bootstrapReady,
        cashflowDir,
        catAddContext,
        catForm,
        categories,
        contributionSources,
        deleteCatFlow,
        deleteInvTypeFlow,
        editingAssetId,
        editingCatId,
        editingExpenseId,
        editingInvTypeId,
        editingInvTypeOrigRateRef,
        editingAssetOrigOverrideRef,
        editingPacId,
        editingRecurringId,
        expForm,
        expSummary,
        expenses,
        filterCat,
        filterYear,
        investmentTypes,
        invTypeForm,
        monthlyOverviewPrefs,
        pacForm,
        recurringForm,
        setAdjustAssetId,
        setAdjustError,
        setAdjustForm,
        setAppLoading,
        setAssetError,
        setAssetForm,
        setAssetSaving,
        setAssets,
        setBootstrapReady,
        setCatAddContext,
        setCatAddError,
        setCatForm,
        setCategories,
        setContributionSources,
        setDeleteCatFlow,
        setDeleteExpenseTarget,
        setDeleteInvTypeFlow,
        setDemoConfirm,
        setDemoError,
        setDemoLoading,
        setDemoUnderstood,
        setEditingAssetId,
        setEditingCatId,
        setEditingExpenseId,
        setEditingInvTypeId,
        setEditingPacId,
        setEditingRecurringId,
        setExpError,
        setExpForm,
        setExpandedCats,
        setFetchError,
        setFilterYear,
        setGeneratePacMsg,
        setGenerateRecurringMsg,
        setInvTypeError,
        setInvTypeForm,
        setModalDir,
        setPacError,
        setPacForm,
        setPacSaving,
        setPriceRefreshCounter,
        setRecurringError,
        setRecurringForm,
        setRecurringSaving,
        setRefreshMsg,
        setRefreshing,
        setResetConfirm,
        setResetMsg,
        setResetUnderstood,
        setShowAdjustModal,
        setShowAssetModal,
        setShowCatAddModal,
        setShowExpModal,
        setShowInvTypeModal,
        setShowPacModal,
        setShowRecurringModal,
        setShowTransferModal,
        setSummary,
        setTaxPropagationFlow,
        setTransferError,
        setTransferForm,
        setTransferLoading,
        setTransferWarning,
        summary,
        trendExpenses,
        trendIncomes,
        transferForm,
    } = providerState;
    const {
        apiFetch,
        assetsCacheRef,
        cacheContextRef,
        categoriesCacheRef,
        decimalSeparator,
        enabledFeatures,
        fetchGrants,
        guardDemo,
        isAuthenticated,
        summaryCacheRef,
        transactionPrefs,
        user,
        viewAs,
    } = sessionController;
    const { contextValue: dataContext } = dataControllers;
    const {
        fetchAllocationData,
        fetchAssets,
        fetchBudgets,
        fetchCategories,
        fetchContributionSources,
        fetchExpSummary,
        fetchExpSummaryCurrentMonth,
        fetchExpenses,
        fetchFireGoal,
        fetchInvestmentTypes,
        fetchMonthlyOverview,
        fetchPortfolioHistory,
        fetchPortfolioSummary,
        fetchProfile,
        fetchRecurringExpenses,
        fetchRecurringInvestmentPlans,
        fetchRecurringStatus,
        fetchTrends,
        refreshAfter,
    } = dataContext;
    const recurringActionsController = useRecurringActions({
        apiFetch,
        decimalSeparator,
        editingPacId,
        editingRecurringId,
        fetchRecurringExpenses,
        fetchRecurringInvestmentPlans,
        guardDemo,
        pacForm,
        recurringForm,
        refreshAfter,
        setEditingPacId,
        setEditingRecurringId,
        setGeneratePacMsg,
        setGenerateRecurringMsg,
        setPacError,
        setPacForm,
        setPacSaving,
        setRecurringError,
        setRecurringForm,
        setRecurringSaving,
        setShowPacModal,
        setShowRecurringModal,
        T,
    });
    useAppBootstrap({
        assetsCacheRef,
        bootstrapReady,
        cacheContextRef,
        categoriesCacheRef,
        fetchAllocationData,
        fetchAssets,
        fetchBudgets,
        fetchCategories,
        fetchContributionSources,
        fetchExpSummary,
        fetchExpSummaryCurrentMonth,
        fetchExpenses,
        fetchFireGoal,
        fetchGrants,
        fetchInvestmentTypes,
        fetchMonthlyOverview,
        fetchPortfolioHistory,
        fetchPortfolioSummary,
        fetchProfile,
        fetchRecurringExpenses,
        fetchRecurringInvestmentPlans,
        fetchRecurringStatus,
        fetchTrends,
        isAuthenticated,
        monthlyOverviewPrefs,
        setAppLoading,
        setAssets,
        setBootstrapReady,
        setCategories,
        setContributionSources,
        setFetchError,
        setSummary,
        summaryCacheRef,
        T,
        user,
        viewAs,
    });

    const importTickerController = useImportAndTicker({
        apiFetch,
        assetForm,
        bankAccounts: groupAssets(assets).bankAccounts,
        categories,
        refreshAfter,
        setAssetForm,
        T,
    });
    const { setTickerQuery, setTickerResults, setTickerSearchOrigin } =
        importTickerController;

    const financialActionsController = useFinancialActions({
        adjustAssetId,
        adjustForm,
        apiFetch,
        assetForm,
        assetSaving,
        cashflowDir,
        categories,
        contributionSources,
        decimalSeparator,
        editingAssetId,
        editingAssetOrigOverrideRef,
        editingExpenseId,
        expForm,
        guardDemo,
        investmentTypes,
        refreshAfter,
        setAdjustAssetId,
        setAdjustError,
        setAdjustForm,
        setAssetError,
        setAssetForm,
        setAssetSaving,
        setDeleteExpenseTarget,
        setEditingAssetId,
        setEditingExpenseId,
        setExpError,
        setExpForm,
        setModalDir,
        setPriceRefreshCounter,
        setRefreshing,
        setRefreshMsg,
        setShowAdjustModal,
        setShowAssetModal,
        setShowExpModal,
        setShowTransferModal,
        setTaxPropagationFlow,
        setTickerQuery,
        setTickerResults,
        setTickerSearchOrigin,
        setTransferError,
        setTransferForm,
        setTransferLoading,
        setTransferWarning,
        T,
        transactionPrefs,
        transferForm,
    });
    const catalogActionsController = useCatalogActions({
        apiFetch,
        catAddContext,
        categories,
        catForm,
        deleteCatFlow,
        deleteInvTypeFlow,
        editingCatId,
        editingInvTypeId,
        editingInvTypeOrigRateRef,
        guardDemo,
        invTypeForm,
        refreshAfter,
        setCatAddContext,
        setCatAddError,
        setCatForm,
        setDeleteCatFlow,
        setDeleteInvTypeFlow,
        setEditingCatId,
        setEditingInvTypeId,
        setExpandedCats,
        setInvTypeError,
        setInvTypeForm,
        setShowCatAddModal,
        setShowInvTypeModal,
        setTaxPropagationFlow,
        T,
    });
    const resetActionsController = useResetActions({
        apiFetch,
        refreshAfter,
        setDemoConfirm,
        setDemoError,
        setDemoLoading,
        setDemoUnderstood,
        setResetConfirm,
        setResetMsg,
        setResetUnderstood,
        T,
    });
    const derivedDataController = useDerivedAppData({
        MONTHS,
        T,
        assetForm,
        assets,
        cashflowDir,
        categories,
        enabledFeatures,
        expSummary,
        expenses,
        filterCat,
        filterYear,
        investmentTypes,
        setFilterYear,
        summary,
        trendExpenses,
        trendIncomes,
    });
    return {
        contextValue: {
            ...recurringActionsController,
            ...importTickerController,
            ...financialActionsController,
            ...catalogActionsController,
            ...resetActionsController,
            ...derivedDataController,
        },
    };
}

export type AppActionControllers = ReturnType<typeof useAppActionControllers>;
