# Generated by Django 6.0.7 on 2026-07-28 06:45

import django.db.models.deletion
import fininzen.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expenses", "0015_remove_expense_expense_amount_positive_and_more"),
        ("portfolio", "0047_owner_cascade_on_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=80)),
                ("color", models.CharField(default="#8e8e8e", max_length=7)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SplitGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("icon", models.CharField(default="👥", max_length=10)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_groups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SplitExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("exact", "Exact amounts"),
                            ("percentage", "Percentage"),
                            ("shares", "Shares/weights"),
                        ],
                        default="equal",
                        max_length=10,
                    ),
                ),
                ("notes", fininzen.fields.EncryptedTextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_expenses",
                        to="expenses.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_split_expenses",
                        to="portfolio.asset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="splitting.splitgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SplitParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to="splitting.splitcontact",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="splitting.splitgroup",
                    ),
                ),
                (
                    "standalone_expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adhoc_participants",
                        to="splitting.splitexpense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SplitExpenseShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "raw_input",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_payer", models.BooleanField(default=False)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="splitting.splitexpense",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shares",
                        to="splitting.splitparticipant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SplitPartnerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_links_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_links_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="splitcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("linked_user__isnull", False)),
                fields=("owner", "linked_user"),
                name="uniq_split_contact_owner_linked_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="split_expense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("group__isnull", False), ("standalone_expense__isnull", True)
                    ),
                    models.Q(
                        ("group__isnull", True), ("standalone_expense__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="splitparticipant_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("contact__isnull", True), ("user__isnull", False)),
                    models.Q(("contact__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="splitparticipant_exactly_one_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("group", "user"),
                name="uniq_group_member_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contact__isnull", False)),
                fields=("group", "contact"),
                name="uniq_group_member_contact",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitexpenseshare",
            constraint=models.UniqueConstraint(
                fields=("expense", "participant"),
                name="uniq_split_share_expense_participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitexpenseshare",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_payer", True)),
                fields=("expense",),
                name="uniq_split_expense_single_payer",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitexpenseshare",
            constraint=models.CheckConstraint(
                condition=models.Q(("share_amount__gte", 0)),
                name="split_share_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitpartnerlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("requester", models.F("recipient")), _negated=True),
                name="split_link_no_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitpartnerlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("requester", "recipient"),
                name="uniq_pending_split_partner_link",
            ),
        ),
    ]
