# Generated by Django 6.0.7 on 2026-07-28 07:13

import django.db.models.deletion
import fininzen.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0048_assettransaction_source_split_expense_and_more"),
        ("splitting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("notes", fininzen.fields.EncryptedTextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_settlements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="splitting.splitgroup",
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_split_settlements",
                        to="portfolio.asset",
                    ),
                ),
                (
                    "payee_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="splitting.splitcontact",
                    ),
                ),
                (
                    "payee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_settlements_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="splitting.splitcontact",
                    ),
                ),
                (
                    "payer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_settlements_paid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="split_settlement_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("payer_contact__isnull", True),
                                ("payer_user__isnull", False),
                            ),
                            models.Q(
                                ("payer_contact__isnull", False),
                                ("payer_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="split_settlement_exactly_one_payer_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("payee_contact__isnull", True),
                                ("payee_user__isnull", False),
                            ),
                            models.Q(
                                ("payee_contact__isnull", False),
                                ("payee_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="split_settlement_exactly_one_payee_identity",
                    ),
                ],
            },
        ),
    ]
