# Generated by Django 6.0.7 on 2026-07-28 07:50

import django.db.models.deletion
import fininzen.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0015_remove_expense_expense_amount_positive_and_more"),
        ("portfolio", "0049_assettransaction_source_split_settlement_and_more"),
        ("splitting", "0002_splitsettlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitRecurringExpenseParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_input",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("is_payer", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="splitexpense",
            name="recurring_occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SplitRecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", fininzen.fields.EncryptedTextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("exact", "Exact amounts"),
                            ("percentage", "Percentage"),
                            ("shares", "Shares/weights"),
                        ],
                        default="equal",
                        max_length=10,
                    ),
                ),
                ("day_of_month", models.IntegerField(default=1)),
                ("month_of_year", models.IntegerField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_recurring_expenses",
                        to="expenses.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_recurring_expenses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to="splitting.splitgroup",
                    ),
                ),
                (
                    "linked_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="split_recurring_expenses",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "id"],
            },
        ),
        migrations.AddField(
            model_name="splitexpense",
            name="recurring_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_expenses",
                to="splitting.splitrecurringexpense",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitexpense",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("recurring_occurrence_date__isnull", False),
                    ("recurring_source__isnull", False),
                ),
                fields=("recurring_source", "recurring_occurrence_date"),
                name="uniq_split_rec_occ",
            ),
        ),
        migrations.AddField(
            model_name="splitrecurringexpenseparticipant",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recurring_templates",
                to="splitting.splitparticipant",
            ),
        ),
        migrations.AddField(
            model_name="splitrecurringexpenseparticipant",
            name="recurring",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_templates",
                to="splitting.splitrecurringexpense",
            ),
        ),
        migrations.AddIndex(
            model_name="splitrecurringexpense",
            index=models.Index(
                fields=["group", "status", "is_active", "start_date"],
                name="splitting_s_group_i_a3f8a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitrecurringexpense",
            index=models.Index(
                fields=["group", "start_date", "end_date"],
                name="splitting_s_group_i_f800e6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitrecurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="split_recurringexpense_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitrecurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="split_recurringexpense_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitrecurringexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("month_of_year__isnull", True),
                    models.Q(("month_of_year__gte", 1), ("month_of_year__lte", 12)),
                    _connector="OR",
                ),
                name="split_recurringexpense_month_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="splitrecurringexpenseparticipant",
            constraint=models.UniqueConstraint(
                fields=("recurring", "participant"), name="uniq_split_rec_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="splitrecurringexpenseparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_payer", True)),
                fields=("recurring",),
                name="uniq_split_rec_single_payer",
            ),
        ),
    ]
