# Generated by Django 6.0.7 on 2026-07-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splitting", "0003_splitrecurringexpenseparticipant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="splitexpenseshare",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="splitting.splitparticipant",
            ),
        ),
        migrations.AlterField(
            model_name="splitrecurringexpenseparticipant",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_templates",
                to="splitting.splitparticipant",
            ),
        ),
    ]
