# Generated by Django 4.2.30 on 2026-04-22 17:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ticker", models.CharField(blank=True, default="", max_length=20)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("ETF", "ETF"),
                            ("STOCK", "Azione"),
                            ("BOND", "Obbligazione"),
                            ("FUND", "Fondo (aggiornamento manuale)"),
                            ("REAL_ESTATE", "Immobile"),
                            ("PRIVATE_EQUITY", "Private Equity"),
                            ("ART", "Arte / Collezionismo"),
                            ("CRYPTO", "Criptovaluta"),
                            ("CASH", "Liquidità"),
                        ],
                        default="ETF",
                        max_length=20,
                    ),
                ),
                ("is_liquid", models.BooleanField(default=True)),
                (
                    "shares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "invested_capital",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("last_price_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Asset",
                "ordering": ["-current_value"],
            },
        ),
    ]
