# Generated by Django 4.2.30 on 2026-04-23 20:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_portfoliosnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliosnapshot",
            name="snapshot_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="AssetTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")],
                        default="buy",
                        max_length=4,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shares",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "price_per_share",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transazione",
                "verbose_name_plural": "Transazioni",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
