# Generated by Django 4.2.30 on 2026-04-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_portfoliosnapshot_snapshot_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("close", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["asset", "date"], name="portfolio_a_asset_i_f0af3d_idx"
                    )
                ],
                "unique_together": {("asset", "date")},
            },
        ),
    ]
