# Generated by Django 4.2.30 on 2026-04-24 11:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_assetpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="isin",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="asset",
            name="current_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="invested_capital",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
