# Generated by Django 4.2.30 on 2026-04-24 12:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_asset_isin_alter_asset_current_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "investment_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_target",
                        to="portfolio.investmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation Target",
                "verbose_name_plural": "Allocation Targets",
            },
        ),
    ]
