# Generated by Django 4.2.30 on 2026-04-25 10:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_expense_linked_asset"),
        ("portfolio", "0007_allocationtarget"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="tracking_type",
            field=models.CharField(
                choices=[("AUTO", "Automatico (yfinance)"), ("MANUAL", "Manuale")],
                default="AUTO",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="assettransaction",
            name="source_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_transactions",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="investmenttype",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="assettransaction",
            name="price_per_share",
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name="assettransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("cash_in", "Cash In"),
                    ("cash_out", "Cash Out"),
                    ("adjustment", "Adjustment"),
                ],
                default="buy",
                max_length=12,
            ),
        ),
    ]
