# Generated by Django 4.2.30 on 2026-04-25 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio",
            "0008_asset_tracking_type_assettransaction_source_expense_and_more",
        ),
    ]

    def set_tracking_type(apps, schema_editor):
        Asset = apps.get_model("portfolio", "Asset")
        Asset.objects.filter(ticker="").update(tracking_type="MANUAL")
        Asset.objects.exclude(ticker="").update(tracking_type="AUTO")

    operations = [
        migrations.RunPython(set_tracking_type, migrations.RunPython.noop),
    ]
