# Generated by Django 4.2.30 on 2026-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_set_tracking_type_from_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmenttype",
            name="is_bank_account",
            field=models.BooleanField(default=False),
        ),
    ]
