# Generated by Django 4.2.30 on 2026-04-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_investmenttype_is_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettransaction",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_txs",
                to="portfolio.assettransaction",
            ),
        ),
    ]
