# Generated by Django 4.2.30 on 2026-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_assettransaction_derived_from"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["asset", "date"], name="portfolio_a_asset_i_f1d252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["source_expense"], name="portfolio_a_source__3a5f16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["derived_from"], name="portfolio_a_derived_d38bd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliosnapshot",
            index=models.Index(
                fields=["snapshot_date"], name="portfolio_p_snapsho_8bcfbc_idx"
            ),
        ),
    ]
