# Generated by Django 4.2.30 on 2026-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_assettransaction_portfolio_a_asset_i_f1d252_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="by_asset",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="by_asset_class",
            field=models.JSONField(default=dict),
        ),
    ]
