# Generated by Django 4.2.30 on 2026-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0013_portfoliosnapshot_by_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="current_value_eur",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
