# Generated by Django 4.2.30 on 2026-04-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0014_asset_current_value_eur"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"investment_type__is_bank_account": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_investments",
                to="portfolio.asset",
            ),
        ),
    ]
