# Generated by Django 4.2.30 on 2026-04-29 21:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0015_asset_source_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_invalidation_reason",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("source_version", models.CharField(default="v1", max_length=10)),
            ],
            options={
                "verbose_name": "Dashboard Summary",
            },
        ),
        migrations.CreateModel(
            name="FireSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_age", models.PositiveSmallIntegerField(default=30)),
                ("retirement_age", models.PositiveSmallIntegerField(default=65)),
                (
                    "withdrawal_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.04"), max_digits=5
                    ),
                ),
                (
                    "annual_expenses_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Se impostato, sovrascrive la media degli ultimi 12 mesi da Expense.",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "growth_rate_bear",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.04"), max_digits=5
                    ),
                ),
                (
                    "growth_rate_base",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.07"), max_digits=5
                    ),
                ),
                (
                    "growth_rate_bull",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.10"), max_digits=5
                    ),
                ),
                (
                    "inflation_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.02"), max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "FIRE Settings",
            },
        ),
    ]
