# Generated by Django 4.2.30 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0017_assign_owner_to_first_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dashboardsummary",
            constraint=models.UniqueConstraint(
                fields=("owner",), name="unique_dashboard_summary_owner"
            ),
        ),
    ]
