# Generated by Django 4.2.30 on 2026-05-06 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0018_dashboard_summary_unique_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="FXRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(default="EUR", max_length=3)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FX Rate History",
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "date"],
                        name="portfolio_f_from_cu_dc0d8a_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "date", "owner")},
            },
        ),
    ]
