# Generated by Django 4.2.30 on 2026-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0019_fx_rate_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="firesettings",
            name="net_worth_goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
