# Generated by Django 4.2.30 on 2026-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0020_add_net_worth_goal_to_firesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettransaction",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
