# Generated by Django 4.2.30 on 2026-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0021_assettransaction_is_verified"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fxratehistory",
            name="portfolio_f_from_cu_dc0d8a_idx",
        ),
        migrations.AddIndex(
            model_name="fxratehistory",
            index=models.Index(
                fields=["owner", "from_currency", "to_currency", "date"],
                name="portfolio_f_owner_i_2dbccd_idx",
            ),
        ),
    ]
