# Generated by Django 4.2.30 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0022_fxratehistory_add_owner_to_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["owner", "date"],
                name="portfolio_a_owner_i_3f0df2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["owner", "transaction_type", "date"],
                name="portfolio_a_owner_i_eae2cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["owner", "is_verified", "date"],
                name="portfolio_a_owner_i_313d81_idx",
            ),
        ),
    ]
