# Generated by Django 4.2.30 on 2026-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0023_assettransaction_owner_filter_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assetpricehistory",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="fxratehistory",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="assetpricehistory",
            constraint=models.UniqueConstraint(
                fields=("asset", "date"), name="unique_assetpricehistory_asset_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="fxratehistory",
            constraint=models.UniqueConstraint(
                fields=("from_currency", "to_currency", "date", "owner"),
                name="unique_fxratehistory_pair_date_owner",
            ),
        ),
    ]
