# Generated by Django 4.2.30 on 2026-05-21 05:52
# AUDIT M4 — current_value_eur becomes NOT NULL default 0.
# Backfill any pre-existing NULL rows with current_value before altering field.

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


def backfill_current_value_eur(apps, schema_editor):
    Asset = apps.get_model("portfolio", "Asset")
    # If FX data isn't available yet, fall back to current_value as a best-guess
    # (same fallback recompute_from_transactions uses on FX failure).
    for asset in Asset.objects.filter(current_value_eur__isnull=True):
        asset.current_value_eur = asset.current_value or Decimal("0")
        asset.save(update_fields=["current_value_eur"])


def noop_reverse(apps, schema_editor):
    # Reversing to nullable is harmless; no row data to restore.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0024_alter_assetpricehistory_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_current_value_eur, noop_reverse),
        migrations.AlterField(
            model_name="asset",
            name="current_value_eur",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
