# Generated by Django 6.0.5 on 2026-06-01 16:48

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_portfolio_integrity(apps, schema_editor):
    Asset = apps.get_model("portfolio", "Asset")
    AssetPriceHistory = apps.get_model("portfolio", "AssetPriceHistory")
    AssetTransaction = apps.get_model("portfolio", "AssetTransaction")
    FireSettings = apps.get_model("portfolio", "FireSettings")
    PortfolioSnapshot = apps.get_model("portfolio", "PortfolioSnapshot")

    for asset in Asset.objects.all().iterator():
        if not asset.currency or asset.currency == "EUR":
            asset.current_value_eur = asset.current_value
            asset.invested_capital_eur = asset.invested_capital
        else:
            # Existing non-EUR values may have been produced by the removed 1:1 fallback.
            asset.current_value_eur = None
            asset.invested_capital_eur = None
        asset.save(update_fields=["current_value_eur", "invested_capital_eur"])

    for tx in AssetTransaction.objects.filter(owner__isnull=True).select_related(
        "asset"
    ):
        if tx.asset.owner_id:
            tx.owner_id = tx.asset.owner_id
            tx.save(update_fields=["owner"])
    for point in AssetPriceHistory.objects.filter(owner__isnull=True).select_related(
        "asset"
    ):
        if point.asset.owner_id:
            point.owner_id = point.asset.owner_id
            point.save(update_fields=["owner"])

    for snap in PortfolioSnapshot.objects.all().iterator():
        snap.snapshot_day = snap.snapshot_date.date()
        snap.save(update_fields=["snapshot_day"])
    duplicate_keys = (
        PortfolioSnapshot.objects.values("owner_id", "snapshot_day")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for key in duplicate_keys:
        ids = list(
            PortfolioSnapshot.objects.filter(
                owner_id=key["owner_id"],
                snapshot_day=key["snapshot_day"],
            )
            .order_by("-snapshot_date", "-id")
            .values_list("id", flat=True)
        )
        PortfolioSnapshot.objects.filter(id__in=ids[1:]).delete()

    duplicate_fire_owners = (
        FireSettings.objects.exclude(owner_id=None)
        .values("owner_id")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )
    for key in duplicate_fire_owners:
        ids = list(
            FireSettings.objects.filter(owner_id=key["owner_id"])
            .order_by("-id")
            .values_list("id", flat=True)
        )
        FireSettings.objects.filter(id__in=ids[1:]).delete()

    invalid_shares = AssetTransaction.objects.filter(shares__lte=0).count()
    invalid_amounts = (
        AssetTransaction.objects.exclude(transaction_type="adjustment")
        .filter(price_per_share__lte=0)
        .count()
    )
    zero_adjustments = AssetTransaction.objects.filter(
        transaction_type="adjustment", price_per_share=0
    ).count()
    if invalid_shares or invalid_amounts or zero_adjustments:
        raise RuntimeError(
            "Cannot add transaction constraints: repair existing rows first. "
            f"shares_non_positive={invalid_shares}, "
            f"amounts_non_positive={invalid_amounts}, "
            f"zero_adjustments={zero_adjustments}"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0011_budget_budget_amount_positive_and_more"),
        ("portfolio", "0028_asset_price_source_auto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="balance_as_of",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="invested_capital_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="portfoliosnapshot",
            name="snapshot_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="current_value_eur",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.RunPython(backfill_portfolio_integrity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("shares__gt", 0)),
                name="assettransaction_shares_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("transaction_type", "adjustment"),
                        models.Q(
                            ("price_per_share__gt", 0),
                            ("price_per_share__lt", 0),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("transaction_type", "adjustment"), _negated=True),
                        ("price_per_share__gt", 0),
                    ),
                    _connector="OR",
                ),
                name="assettransaction_amount_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="firesettings",
            constraint=models.UniqueConstraint(
                fields=("owner",), name="unique_fire_settings_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliosnapshot",
            constraint=models.UniqueConstraint(
                fields=("owner", "snapshot_day"), name="unique_snapshot_owner_day"
            ),
        ),
    ]
