# Generated by Codex on 2026-06-04

from django.db import migrations


def verify_adjustment_transactions(apps, schema_editor):
    AssetTransaction = apps.get_model("portfolio", "AssetTransaction")
    AssetTransaction.objects.filter(
        transaction_type="adjustment",
        is_verified=False,
    ).update(is_verified=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0029_asset_balance_as_of_asset_invested_capital_eur_and_more"),
    ]

    operations = [
        migrations.RunPython(verify_adjustment_transactions, noop_reverse),
    ]
