# Generated by Django 6.0.5 on 2026-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0033_rename_contribution_source_defaults_to_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
