# Generated by Django 6.0.5 on 2026-06-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0034_asset_archived_at_asset_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="previous_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"investment_type__is_bank_account": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_investments",
                to="portfolio.asset",
            ),
        ),
    ]
