# Generated by Django 6.0.5 on 2026-06-07 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0011_budget_budget_amount_positive_and_more"),
        ("portfolio", "0037_clear_legacy_transfer_and_opening_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_expense__isnull", False)),
                fields=("source_expense",),
                name="unique_shadow_tx_per_expense",
            ),
        ),
    ]
