# Generated by Django 6.0.6 on 2026-06-14 20:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0012_recurringexpense_frequency_and_more"),
        ("portfolio", "0039_opening_balance_baseline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetpricehistory",
            name="open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="assettransaction",
            name="recurring_occurrence_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RecurringInvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMIANNUAL", "Semiannual"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("day_of_month", models.PositiveSmallIntegerField(default=1)),
                (
                    "anchor_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("generated_transactions_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_investment_plans",
                        to="portfolio.asset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funded_recurring_investment_plans",
                        to="portfolio.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring Investment Plan",
                "verbose_name_plural": "Recurring Investment Plans",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="assettransaction",
            name="recurring_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_transactions",
                to="portfolio.recurringinvestmentplan",
            ),
        ),
        migrations.AddIndex(
            model_name="assettransaction",
            index=models.Index(
                fields=["owner", "recurring_plan", "recurring_occurrence_date"],
                name="portfolio_a_recplan_occ_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("derived_from__isnull", True),
                    ("recurring_occurrence_date__isnull", False),
                    ("recurring_plan__isnull", False),
                ),
                fields=("owner", "recurring_plan", "recurring_occurrence_date"),
                name="unique_pac_occ_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvestmentplan",
            index=models.Index(
                fields=["owner", "status", "is_active", "start_date"],
                name="portfolio_r_owner_i_b71a06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringinvestmentplan",
            index=models.Index(
                fields=["owner", "asset", "status"],
                name="portfolio_r_owner_i_41175c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvestmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="recinvplan_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvestmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 31)),
                name="recinvplan_day_of_month_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvestmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("day_of_week__isnull", True),
                    models.Q(("day_of_week__gte", 1), ("day_of_week__lte", 7)),
                    _connector="OR",
                ),
                name="recinvplan_day_of_week_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvestmentplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("anchor_month__isnull", True),
                    models.Q(("anchor_month__gte", 1), ("anchor_month__lte", 12)),
                    _connector="OR",
                ),
                name="recinvplan_anchor_month_valid",
            ),
        ),
    ]
