# Generated by Django 6.0.6 on 2026-06-16 23:03

import fininzen.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0043_assettransaction_tax_amount_is_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="notes",
            field=fininzen.fields.EncryptedTextField(blank=True, default=""),
        ),
    ]
