# Generated by Django 6.0.6 on 2026-06-17 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0013_alter_expensedescriptionsuggestion_options_and_more"),
        ("portfolio", "0044_alter_asset_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                condition=models.Q(("is_archived", False)),
                fields=["owner"],
                name="asset_active_by_owner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_percent__gte", 0)),
                name="allocationtarget_target_percent_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shares__isnull", True), ("shares__gte", 0), _connector="OR"
                ),
                name="asset_shares_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_per_share__isnull", True),
                    ("price_per_share__gte", 0),
                    _connector="OR",
                ),
                name="asset_price_per_share_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate_override__isnull", True),
                    ("tax_rate_override__gte", 0),
                    _connector="OR",
                ),
                name="asset_tax_rate_override_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee__gte", 0)),
                name="assettransaction_fee_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)),
                name="assettransaction_tax_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="investmenttype",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0)),
                name="investmenttype_tax_rate_non_negative",
            ),
        ),
    ]
