# Generated by Django 6.0.7 on 2026-07-28 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0015_remove_expense_expense_amount_positive_and_more"),
        ("portfolio", "0047_owner_cascade_on_delete"),
        ("splitting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assettransaction",
            name="source_split_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_transactions",
                to="splitting.splitexpense",
            ),
        ),
        migrations.AddConstraint(
            model_name="assettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_split_expense__isnull", False)),
                fields=("source_split_expense",),
                name="unique_shadow_tx_per_split_expense",
            ),
        ),
    ]
