import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
    {
        ignores: [
            ".next/**",
            "node_modules/**",
            "src/api/schema.d.ts", // auto-generated by openapi-typescript
        ],
    },
    ...nextCoreWebVitals,
    ...nextTypescript,
    {
        files: ["src/**/*.{ts,tsx}"],
        rules: {
            // Same hard line as the Vite app: the typed OpenAPI contract means
            // there is never a reason to fall back to `any`.
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/consistent-type-imports": "error",
            // Next 16 brings the React Compiler diagnostics into the default
            // preset. Keep the existing effect/ref patterns valid during this
            // dependency migration; they are intentional throughout the app.
            "react-hooks/immutability": "off",
            "react-hooks/refs": "off",
            "react-hooks/set-state-in-effect": "off",
        },
    },
];

export default eslintConfig;
