import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
    {
        ignores: [
            ".next/**",
            "node_modules/**",
            "src/api/schema.d.ts", // auto-generated by openapi-typescript
        ],
    },
    ...compat.extends("next/core-web-vitals", "next/typescript"),
    {
        files: ["src/**/*.{ts,tsx}"],
        rules: {
            // Same hard line as the Vite app: the typed OpenAPI contract means
            // there is never a reason to fall back to `any`.
            "@typescript-eslint/no-explicit-any": "error",
            "@typescript-eslint/consistent-type-imports": "error",
        },
    },
];

export default eslintConfig;
